# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bcc25aa8-2033-4e31-ab06-32fd6446ef96";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bcc25aa8-2033-4e31-ab06-32fd6446ef96".device = "/dev/disk/by-uuid/bcc25aa8-2033-4e31-ab06-32fd6446ef96";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BEE7-6501";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-7282faec-2147-4fdf-b6d8-6529460f9fe1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
