# Hand-written, not generated by `nixos-generate-config`.
#
# BOOTSTRAP.md tells you to regenerate this on a new machine, and that is still
# the right first move. This copy is kept by hand because the generator emits
# bare `subvol=` options and would drop the compression and discard settings
# below every time it ran.
#
# Describes: NixOS on the Samsung NVMe (nvme0n1). The 1TB WD HDD that this
# system used to live on is not referenced here at all.
{ config, lib, pkgs, modulesPath, ... }:

let
  # One btrfs filesystem, three subvolumes. Same device UUID for all three.
  btrfsDevice = "/dev/disk/by-uuid/d1aa0f8a-09b3-4ef2-9622-7962eb1fb511";

  # zstd:1 is the cheap end of the range: it cuts bytes written to the SSD for
  # very little CPU, which matters most for the many small files in /nix.
  # discard=async needs allowDiscards on the LUKS container below to reach the
  # device at all.
  btrfsOpts = [ "noatime" "compress=zstd:1" "ssd" "discard=async" ];
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Unchanged from the generated HDD version: same machine, same controllers.
  # "nvme" was already in this list, which is why the NVMe was visible all along.
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = btrfsOpts ++ [ "subvol=@" ];
  };

  fileSystems."/home" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = btrfsOpts ++ [ "subvol=@home" ];
  };

  fileSystems."/nix" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = btrfsOpts ++ [ "subvol=@nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4C62-FCDA";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # Opens as /dev/mapper/nixroot. The filesystems above find themselves by UUID,
  # so this name is cosmetic.
  #
  # allowDiscards lets TRIM through the encryption layer. It is what makes
  # discard=async above do anything. The tradeoff is the usual one: an attacker
  # with the raw device can see which blocks are in use, though not what is in
  # them.
  #
  # The TPM was enrolled after the first successful boot, so a bad enrolment
  # could never lock you out of a system you had not yet booted.
  boot.initrd.luks.devices."nixroot" = {
    device = "/dev/disk/by-uuid/e50820ae-33cb-4103-8366-b0c1f58ea084";
    allowDiscards = true;

    # Unlock from the TPM instead of prompting. Enrolled against PCR 7 with
    # systemd-cryptenroll; the passphrase stays in keyslot 0 as the fallback,
    # so a firmware change that breaks the seal costs a prompt, not the disk.
    # Secure Boot is off here, so PCR 7 is never extended: this buys
    # convenience, not protection against someone walking off with the drive.
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };

  # zram (modules/hardware.nix) is the only swap. configuration.nix forces this
  # empty anyway; stating it here keeps the two files from disagreeing.
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
