{
  inputs,
  lib,
  ...
}:

let
  # Nebula's two entry points, imported straight from the store. Everything
  # under them is relative, so the whole theme resolves from wherever the input
  # lands.
  nebulaChrome = "${inputs.zen-nebula}/userChrome.css";
  nebulaContent = "${inputs.zen-nebula}/userContent.css";

  # Nebula's stock tuning values, which upstream expects its mod loader to
  # supply. Imported after Nebula, though the order does not actually matter:
  # the file only defines --var-nebula-*, which Nebula reads and never sets.
  nebulaVars = "${./zen/nebula-vars.css}";

  # The profile's chrome/ files are generated whole rather than appended to, so
  # a bumped zen-nebula input cannot leave a stale store path behind. Anything
  # hand-written in them would be overwritten, which is why the header says so.
  header = ''
    /* Generated by configs/zen.nix. Edits here are lost on the next switch. */
  '';
  userChromeCss = ''
    ${header}@import "${nebulaChrome}";
    @import "${nebulaVars}";
  '';
  userContentCss = ''
    ${header}@import "${nebulaContent}";
  '';
in
{
  # zen is installed from the flake input (modules/packages/external.nix) and
  # its profile is ordinary browser state, so nothing here manages the profile
  # beyond the theming files below.
  #
  # The chrome is skinned with Nebula rather than with noctalia's built-in
  # zenBrowser template, which stays off in configs/theming/noctalia-config.json.
  # That template only recolours zen's existing surfaces, and no arrangement of
  # flat colours gets to the glass look. Nebula is a real material: it blurs
  # with backdrop-filter inside the browser, so the chrome frosts over the page
  # behind it rather than only over the wallpaper.
  #
  # Nebula normally installs through Sine, a mod loader that needs
  # fx-autoconfig. None of that is used here. Its colours are plain custom
  # properties, which zen/nebula-vars.css defines, and its feature toggles are
  # read with @media (-moz-pref(...)), which Firefox evaluates against
  # about:config directly, so prefs in user.js are enough. What is given up is
  # Nebula's own settings UI and its nebula.uc.js, which sets three toolbar
  # attributes that only affect pinned-extension geometry.
  #
  # Nebula runs at its stock values and does not follow the wallpaper. It used
  # to: zen/nebula-vars-template.css rendered the glass and the tab ladder from
  # the noctalia palette. That is gone, along with the noctalia user-template
  # that drove it, so ~/.cache/noctalia/zen-browser/ is now dead and can be
  # deleted by hand.
  #
  # Transparency comes from niri rather than from the browser. zen declares its
  # whole Wayland surface opaque and, measured against a screenshot, keeps doing
  # so even with widget.wayland.opaque-region.enabled off: the toolbar reads an
  # identical value at every x while the wallpaper above it swings across a
  # third of the colour wheel. So the catch-all window-rule in
  # configs/theming/niri.nix does the work at opacity 0.87. That dims the web
  # content along with the chrome, which is a known and accepted cost.

  # toolkit.legacyUserProfileCustomizations.stylesheets gates userChrome.css and
  # userContent.css entirely, and without it none of the above loads. zen does
  # flip it itself when it finds a user stylesheet, but only inside _migrateV1,
  # a one-shot keyed on the profile's migration version, so a profile created
  # before this existed never runs it.
  #
  # browser.tabs.allow_transparent_browser is pinned off rather than dropped.
  # It was one of three prefs this used to write to get the browser to draw its
  # own translucency, and an earlier version of this comment called all three
  # inert once they stopped being written. That was wrong about this one. It
  # takes the background off the <browser> element, which is the page canvas,
  # so a site that paints no background on html or body no longer comes out
  # white: every pixel the page does not paint shows the blurred desktop
  # instead. Legacy sites that colour only their own tables read as though
  # something forced dark mode on them.
  #
  # Dropping the line is not enough, because the browser rewrites prefs.js on
  # exit and a profile that was ever switched on keeps the true there. Writing
  # false is what actually resets it.
  #
  # The other two, zen.widget.linux.transparency and
  # widget.wayland.opaque-region.enabled, are left alone. They really are inert
  # given that niri does the transparency from outside, and the opaque region
  # in particular was measured twice with opposite conclusions, so returning it
  # to its default is a change worth making on its own evidence rather than as
  # a side effect of this fix.
  #
  # user.js rather than prefs.js: the browser rewrites prefs.js on exit and
  # re-reads user.js on every start, so this survives a reset from inside the
  # browser.
  #
  # The glob matches on chrome/ rather than on any directory under
  # ~/.config/zen, which also holds firefox-mpris, native-messaging-hosts and
  # Profile Groups.
  home.activation.zenTheming = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    for chrome in "$HOME"/.config/zen/*/chrome/; do
      [ -d "$chrome" ] || continue
      profile="$(dirname "$chrome")"

      run install -m 644 ${
        builtins.toFile "userChrome.css" userChromeCss
      } "$chrome/userChrome.css"
      run install -m 644 ${
        builtins.toFile "userContent.css" userContentCss
      } "$chrome/userContent.css"

      # Each key is dropped from user.js before its line is appended, so a key
      # already written at the wrong value is corrected rather than duplicated.
      # Appending needs a shell redirect, which `run` cannot wrap without the
      # redirect firing during a dry run too, so the dry run is handled here.
      for pref in ${
        lib.escapeShellArgs [
          "toolkit.legacyUserProfileCustomizations.stylesheets=true"
          "browser.tabs.allow_transparent_browser=false"
        ]
      }; do
        key="''${pref%%=*}"
        line="user_pref(\"$key\", ''${pref#*=});"
        grep -Fqxs "$line" "$profile/user.js" && continue

        if [[ -v DRY_RUN ]]; then
          echo "would set in $profile/user.js: $line"
        else
          if [ -e "$profile/user.js" ]; then
            # grep exits 1 when it prints nothing, which set -e would treat as
            # a failure even though an empty result is a valid rewrite.
            grep -Fv "user_pref(\"$key\"," "$profile/user.js" > "$profile/user.js.tmp" || true
            mv "$profile/user.js.tmp" "$profile/user.js"
          fi
          printf '%s\n' "$line" >> "$profile/user.js"
        fi
      done
    done
  '';
}
