{
  config,
  inputs,
  lib,
  ...
}:

let
  # Nebula's two entry points, imported straight from the store. Everything
  # under them is relative, so the whole theme resolves from wherever the input
  # lands.
  nebulaChrome = "${inputs.zen-nebula}/userChrome.css";
  nebulaContent = "${inputs.zen-nebula}/userContent.css";

  # Rendered by noctalia, imported after Nebula. Only defines --var-nebula-*,
  # which Nebula reads and never sets itself, so the import order between the
  # two does not actually matter.
  nebulaVars = "${config.xdg.cacheHome}/noctalia/zen-browser/nebula-vars.css";

  # The profile's chrome/ files are generated whole rather than appended to, so
  # a bumped zen-nebula input cannot leave a stale store path behind. Anything
  # hand-written in them would be overwritten, which is why the header says so.
  header = ''
    /* Generated by configs/zen.nix. Edits here are lost on the next switch. */
  '';
  userChromeCss = ''
    ${header}@import "${nebulaChrome}";
    @import "${nebulaVars}";
  '';
  userContentCss = ''
    ${header}@import "${nebulaContent}";
  '';
in
{
  # zen is installed from the flake input (modules/packages/external.nix) and
  # its profile is ordinary browser state, so nothing here manages the profile
  # beyond the theming files below.
  #
  # The chrome is skinned with Nebula rather than with noctalia's built-in
  # zenBrowser template, which stays off in configs/theming/noctalia-config.json.
  # That template only recolours zen's existing surfaces, and no arrangement of
  # flat colours gets to the glass look. Nebula is a real material: it blurs
  # with backdrop-filter inside the browser, so the chrome frosts over the page
  # behind it rather than only over the wallpaper.
  #
  # Nebula normally installs through Sine, a mod loader that needs
  # fx-autoconfig. None of that is used here. Its colours are plain custom
  # properties, which the template below defines, and its feature toggles are
  # read with @media (-moz-pref(...)), which Firefox evaluates against
  # about:config directly, so prefs in user.js are enough. What is given up is
  # Nebula's own settings UI and its optional nebula.uc.js, which adds
  # behaviour rather than looks.
  programs.noctalia-shell.user-templates.templates.zenNebula = {
    input_path = "${./zen/nebula-vars-template.css}";
    output_path = nebulaVars;
  };

  # Three prefs, all off by default in zen's greprefs.js, and all three are
  # needed before any of the above is visible:
  #
  # toolkit.legacyUserProfileCustomizations.stylesheets gates userChrome.css
  # and userContent.css entirely. zen does flip it itself when it finds a user
  # stylesheet, but only inside _migrateV1, a one-shot keyed on the profile's
  # migration version, so a profile created before this existed never runs it.
  #
  # zen.widget.linux.transparency drops the opaque background off #main-window,
  # which is what lets any alpha in the theme reach the compositor at all.
  #
  # widget.wayland.opaque-region.enabled is off beside it. Firefox tells the
  # compositor which part of its surface is fully opaque, as a hint that lets
  # the compositor skip blending and skip drawing what is behind, and it claims
  # the whole window. Turning that off is necessary but, measured on this build,
  # not sufficient: with all four prefs set and zen on native Wayland, sampling
  # a screenshot along the toolbar gives the same value at every x while the
  # wallpaper directly above it swings from #86CBE1 to #4A495E. Not one pixel of
  # bleed. Something below the chrome is still opaque and it is not this. The
  # pref stays because it is a real precondition, not because it was the fix.
  # The only see-through zen has ever had came from niri's own opacity, applied
  # on top of the surface rather than through it.
  #
  # browser.tabs.allow_transparent_browser lets the content area go
  # transparent, which is what Nebula's backdrop-filter needs something to
  # frost over.
  #
  # user.js rather than prefs.js: the browser rewrites prefs.js on exit and
  # re-reads user.js on every start, so these survive a reset from inside the
  # browser.
  #
  # The glob matches on chrome/ rather than on any directory under
  # ~/.config/zen, which also holds firefox-mpris, native-messaging-hosts and
  # Profile Groups.
  home.activation.zenTheming = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    for chrome in "$HOME"/.config/zen/*/chrome/; do
      [ -d "$chrome" ] || continue
      profile="$(dirname "$chrome")"

      run install -m 644 ${
        builtins.toFile "userChrome.css" userChromeCss
      } "$chrome/userChrome.css"
      run install -m 644 ${
        builtins.toFile "userContent.css" userContentCss
      } "$chrome/userContent.css"

      # Appending needs a shell redirect, which `run` cannot wrap without the
      # redirect firing during a dry run too, so the dry run is handled here.
      for pref in \
        'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' \
        'user_pref("zen.widget.linux.transparency", true);' \
        'user_pref("widget.wayland.opaque-region.enabled", false);' \
        'user_pref("browser.tabs.allow_transparent_browser", true);'
      do
        grep -Fqs "$pref" "$profile/user.js" && continue
        if [[ -v DRY_RUN ]]; then
          echo "would append to $profile/user.js: $pref"
        else
          printf '%s\n' "$pref" >> "$profile/user.js"
        fi
      done
    done
  '';
}
